### ISSUE TITLE
Taxonomy not working in custom post

### ISSUE THREAD

**Issue by skylab11** [yasglobal/permalinks-customizer#11]
Hi, I'm using permalink-customizer but I've some issues.
As you can see from linked images below, I configure taxonomies and custom permalink urls:

![taxonomies](https://user-images.githubusercontent.com/7684871/38020122-bc72e316-3279-11e8-9851-6ef5b704e5f6.jpg)

![permalink_customizer](https://user-images.githubusercontent.com/7684871/38020154-cb449ea2-3279-11e8-8546-7f7b56c4408d.jpg)

![custom_post](https://user-images.githubusercontent.com/7684871/38019932-3e620a88-3279-11e8-9b2e-d6c9a5840df9.jpg)

![400_bad_request](https://user-images.githubusercontent.com/7684871/38020163-d101598e-3279-11e8-9f25-7d7634ad0c90.jpg)

When I regenerate permalink in my "TEST Custom Post" taxonomies don't working and it's not translated:
> https://www.terrachevive.com/clean/%tour_category%/test-custom-post/

Whats's wrong?
Thank's for your attenction.
Best regards
Massimo

**Comment by samiahmedsiddiqui** [comment]
Hi @skylab11 

Thanks for reporting this.

Actually Tour PostType is giving you 404 due to `%tour_category%`. `%tour_category%` is the custom taxonomy and you can't use custom taxonomy in the PostType Settings to auto-generate the Permalinks. Only the provided tags which are available on the Plugins Page and also under the plugin settings can be used.

Custom Taxonomy Tags would be available in the upcoming version of the plugin but till then you can't use that.

Regards,
Sami

**Comment by samiahmedsiddiqui** [comment]
@skylab11 This feature has been added in v2.0.0 and the version i available in WordPress. Please get the latest version of the plugin and use this feature.

Custom Taxonomy Tag can be used as defined here: 
https://github.com/yasglobal/permalinks-customizer#tags-for-posttypes

Use of Custom Taxonomy Tag:
> <%ctax_custom_taxonomy%> : A sanitized version of the custom taxonomy where the taxonomy name is custom_taxonomy. Replace the custom_taxonomy with your appropriate created taxonomy name. If you want to provide the default slug which is used when the category/taxonomy doesn't be selected so, make sure to provide default name/slug which looks like this: <%ctax_custom_taxonomy??sales%>. Value which is written between the ?? and %> is used as default slug.

Thanks,
Sami
