### ISSUE TITLE
Unable to solve plugin implementation with Polylang

### ISSUE THREAD

**Issue by pierrotevrard-idp** [yasglobal/permalinks-customizer#43]
Ok,

I'm trying to configure this plugin with Polylang. I've got:

- Wordpress 5.x as FR installation
- Polylang with FR, EN and DE languages
- Permalinks customizer

I'm trying to have a news available in three languages with these slugs :
- /fr/nos-actualites/picasso
- /en/our-news/picasso
- /de/unsere-news/picasso

So, it's pretty easy to set a post permalinks structure to  `%category%/%postname%/` and - with exepected category data - every link is generated fine, but when I try to access FR and EN version of these posts, I'm redirected to a 404 page with URL "/unsere-news/picasso" (no more language data).

I try to remove automatic redirects, no effect.
I flush permalinks cache, no effect.

I don't know where to look to avoid this redirection, whitout the Permalinks Customizer extension, Wordpress serves three distinct pages for each url "(fr|en|de)/picasso"...

**Comment by pierrotevrard-idp** [comment]
Ok, it may be related to Polylang PRO feature. I close it for now.

**Comment by subfighter3** [comment]
Hi there

I'm experiencing a similar issue either with Polylang or WPML: Permalinks Customizer simply removes any language slug prepended before the original slug.

I'm testing it with all the very latest versions of WP/Polylang Pro/WPML/Permalinks Customizer.

Maybe a new Structure Tag dedicated to an eventual language slug may fix this problem?

Please let me know if I can provide more details in order to let you fix this problem.

thanks in advance
